### ISSUE TITLE
Baselines Training Code

### ISSUE THREAD

**Issue by pratham16cse** [EnyanDai/GANF#3]
Hi,

Great work from the authors and thank you for making the code available. I was wondering whether the training code for the baselines could also be shared? I am working on a variant problem for which I would like to try one of the baselines DeepSVDD or DeepSAD. Since the codebase provides a nice framework to build on, I would highly appreciate it if the baseline training code could also be made available. 
My email id is pratham@cse.iitb.ac.in for further communication.

Thanks a lot.

**Comment by EnyanDai** [comment]
Sorry for the late response. We will release an example of the baseline training code later.
