### ISSUE TITLE
How to use the baseline training code

### ISSUE THREAD

**Issue by limerence0515** [EnyanDai/GANF#5]
Hello,
       Thanks for sharing the code! I found the python code for baselines in the models folder, but I am not sure how to use them. Could you please give some instructions about how to use them to reproduce the result of baselines when you have a moment? 

     Thank you in advance! My email is xijuan.sun@mail.mcgill.ca.

Thank you!

**Comment by EnyanDai** [comment]
Sorry for the late response. We will release an example of the baseline training code later.
